name: 'CI'

on: 
  pull_request:
    types: [review_requested]
jobs:
  tests:
    name: 'Run unit tests'
    runs-on: 'windows-latest'
    steps:
      - uses: 'actions/checkout@v2.1.0'
      - run: 'dotnet test /clp:ErrorsOnly WindowsSolution.sln'